biblioteca/urls.py
from django.conf.urls import url
from django.views.generic.base import TemplateView
from biblioteca.views import (CreateLivro, UpdateLivro, DeleteLivro,
                              ListLivro, CreatePessoa, UpdatePessoa,
                              DeletePessoa, ListPessoa, CreateEmprestimo,
                              UpdateEmprestimo, DeleteEmprestimo,
                              ListEmprestimo)

app_name = "biblioteca"

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='biblioteca/home.html'),
        name='list'),
    url(r'livro/$', ListLivro.as_view(),
        name='list_livro'),
    url(r'livro/create/$', CreateLivro.as_view(),
        name='create_livro'),
    url(r'livro/(?P<pk>\d+)/$', UpdateLivro.as_view(),
        name='update_livro'),
    url(r'livro/delete/(?P<pk>\d+)/$', DeleteLivro.as_view(),
        name='delete_livro'),
    url(r'pessoa/$', ListPessoa.as_view(),
        name='list_pessoa'),
    url(r'pessoa/create/$', CreatePessoa.as_view(),
        name='create_pessoa'),
    url(r'pessoa/(?P<pk>\d+)/$', UpdatePessoa.as_view(),
        name='update_pessoa'),
    url(r'pessoa/delete/(?P<pk>\d+)/$', DeletePessoa.as_view(),
        name='delete_pessoa'),
    url(r'emprestimo/$', ListEmprestimo.as_view(),
        name='list_emprestimo'),
    url(r'emprestimo/create/$', CreateEmprestimo.as_view(),
        name='create_emprestimo'),
    url(r'emprestimo/(?P<pk>\d+)/$',
        UpdateEmprestimo.as_view(),
        name='update_emprestimo'),
    url(r'emprestimo/delete/(?P<pk>\d+)/$',
        DeleteEmprestimo.as_view(),
        name='delete_emprestimo'),
]

mttech/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url('', include('biblioteca.urls')),
]

biblioteca/models.py
from django.urls import reverse
from django.db import models


class Pessoa(models.Model):
    nome = models.CharField(
        max_length=150,
        null=False,
        blank=False
    )

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('biblioteca:list_pessoa')


class Livro(models.Model):
    nome = models.CharField(
        max_length=150,
        null=False,
        blank=False
    )

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('biblioteca:list_livro')


class Emprestimo(models.Model):
    livro = models.ForeignKey(
        Livro,
        unique=True,
        on_delete=models.CASCADE
    )
    pessoa = models.ForeignKey(
        Pessoa,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return "{} - {}".format(self.livro.nome, self.pessoa.nome)

    def get_absolute_url(self):
        return reverse('biblioteca:list_emprestimo')

biblioteca/views.py
from django.urls import reverse
from django.views.generic import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from biblioteca.models import Livro, Pessoa, Emprestimo


class CreateLivro(CreateView):
    model = Livro
    fields = ['nome']
    template_name = 'biblioteca/form_create.html'


class UpdateLivro(UpdateView):
    model = Livro
    fields = ['nome']
    template_name = 'biblioteca/form_update.html'


class DeleteLivro(DeleteView):
    model = Livro
    template_name = 'biblioteca/form_delete.html'

    def get_success_url(self):
        return reverse('biblioteca:list_livro')


class ListLivro(ListView):
    model = Livro


class CreatePessoa(CreateView):
    model = Pessoa
    fields = ['nome']
    template_name = 'biblioteca/form_create.html'


class UpdatePessoa(UpdateView):
    model = Pessoa
    fields = ['nome']
    template_name = 'biblioteca/form_update.html'


class DeletePessoa(DeleteView):
    model = Pessoa
    template_name = 'biblioteca/form_delete.html'

    def get_success_url(self):
        return reverse('biblioteca:list_pessoa')


class ListPessoa(ListView):
    model = Pessoa


class CreateEmprestimo(CreateView):
    model = Emprestimo
    fields = ['livro', 'pessoa']
    template_name = 'biblioteca/form_create.html'


class UpdateEmprestimo(UpdateView):
    model = Emprestimo
    fields = ['livro', 'pessoa']
    template_name = 'biblioteca/form_update.html'


class DeleteEmprestimo(DeleteView):
    model = Emprestimo
    template_name = 'biblioteca/form_delete.html'

    def get_success_url(self):
        return reverse('biblioteca:list_emprestimo')


class ListEmprestimo(ListView):
    model = Emprestimo

biblioteca/templates/biblioteca/emprestimo_list.html
<h1>Emprestimo</h1>
<a href="{% url 'biblioteca:create_emprestimo'%}">Criar</a>
<ul>
{% for emprestimo in object_list %}
    <li>{{ emprestimo.pessoa.nome }} - {{ emprestimo.livro.nome }} <a href="{% url 'biblioteca:update_emprestimo' emprestimo.pk %}">Editar</a> <a href="{% url 'biblioteca:delete_emprestimo' emprestimo.pk %}">Deletar</a> </li>
{% empty %}
    <li>Não tem nem uma Emprestimo cadastrado</li>
{% endfor %}
</ul>
<a href="{% url 'biblioteca:list'%}">Voltar</a>

biblioteca/templates/biblioteca/form_create.html
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Salvar" />
</form>

biblioteca/templates/biblioteca/form_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Tem certeza de que deseja excluir "{{ object }}"?</p>
    <input type="submit" value="Confirmar" />
</form>

biblioteca/templates/biblioteca/form_update.html
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Atualizar" />
</form>

biblioteca/templates/biblioteca/home.html
<h1>Biblioteca</h1>
<ul>
    <li><a href="{% url 'biblioteca:list_livro'%}">Livros</a></li>
    <li><a href="{% url 'biblioteca:list_pessoa'%}">Pessoas</a></li>
    <li><a href="{% url 'biblioteca:list_emprestimo'%}">Emprestimo</a></li>
</ul>

biblioteca/templates/biblioteca/livro_list.html
<h1>Livros</h1>
<a href="{% url 'biblioteca:create_livro'%}">Criar</a>
<ul>
{% for livro in object_list %}
    <li>{{ livro.nome }} <a href="{% url 'biblioteca:update_livro' livro.pk %}">Editar</a> <a href="{% url 'biblioteca:delete_livro' livro.pk %}">Deletar</a> </li>
{% empty %}
    <li>Não tem nem uma Livro cadastrado</li>
{% endfor %}
</ul>
<a href="{% url 'biblioteca:list'%}">Voltar</a>

biblioteca/templates/biblioteca/pessoa_list.html
<h1>Pessoas</h1>
<a href="{% url 'biblioteca:create_pessoa'%}">Criar</a>
<ul>
{% for pessoa in object_list %}
    <li>{{ pessoa.nome }} <a href="{% url 'biblioteca:update_pessoa' pessoa.pk %}">Editar</a> <a href="{% url 'biblioteca:delete_pessoa' pessoa.pk %}">Deletar</a> </li>
{% empty %}
    <li>Não tem nem uma Pessoa cadastrado</li>
{% endfor %}
</ul>
<a href="{% url 'biblioteca:list'%}">Voltar</a>